### ISSUE TITLE
Bug: Starting resources not working on some missions

### ISSUE THREAD

**Issue by AliceVoltaire** [Ziktofel/Archipelago#106]
### What happened?

Some missions do not add the +15 Starting Minerals/Vespene Gas items to the starting resources on a mission.  I loaded each mission and made note of the ones that weren't adding the resources properly.

A Sinister Turn: no Minerals or Vespene
Echoes of the Future: no Minerals of Vespene
Ghosts in the Fog: no Minerals
Harbinger of Oblivion: no Minerals or Vespene
In Utter Darkness: no Minerals or Vespene
Last Stand: no Minerals
Media Blitz: no Minerals or Vespene
Moebius Factor: no Minerals or Vespene
Templar's Charge: no Minerals or Vespene

### What were the expected results?

These missions should be adding the starting resources received from items

### Software

While playing

**Comment by Ziktofel** [comment]
Fixed
