### ISSUE TITLE
Bug: Spear of Adun autocast abilities are still being applied to Terran and Zerg when "Protoss" setting is chosen in the yaml

### ISSUE THREAD

**Issue by AliceVoltaire** [Ziktofel/Archipelago#108]
### What happened?

In two different games I've tested, I've gotten Reconstruction Beam and Overwatch, and they've both been getting applied to my Zerg and Protoss missions when the expectation is that they shouldn't be.

### What were the expected results?

Reconstruction Beam shouldn't be healing my Terran mech if I set it not to

### Software

While playing

**Comment by Ziktofel** [comment]
Fixed
