### ISSUE TITLE
Bug: Protoss Air Attack Upgrade Takes Incorrectly

### ISSUE THREAD

**Issue by Varcklen** [Ziktofel/Archipelago#111]
### What happened?

![456567](https://github.com/Ziktofel/Archipelago/assets/93214632/ce2deea7-82a5-4e42-8321-4a9e35f69c7f)
![5467657](https://github.com/Ziktofel/Archipelago/assets/93214632/9c475b6d-fa08-4677-b393-981fc59806e6)
Playing the template with generic_upgrade_items: bundle_unit_class specified (attack+armor tier upgrades are given together), after receiving the "Air Protoss Upgrade" bundle (the first time) I only received Armor, although I should have received both. When I received it the second time, I got the Attack and Armor as it should be.

Update
The same issue with ground upgrades on [Steps to the Right] mission.
![456546767](https://github.com/Ziktofel/Archipelago/assets/93214632/eecf9b01-9d48-407c-96cb-ac0b78e1d093)

### What were the expected results?

Fix receiving Attack Upgrade for the "Air Protoss Upgrade" bundle in the template with generic_upgrade_items: bundle_unit_class.

### Software

While playing

**Comment by Ziktofel** [comment]
Should be fixed, generate a new game
