### ISSUE TITLE
Bug: [Slayer] Phasing Armor doesn't work correctly

### ISSUE THREAD

**Issue by Varcklen** [Ziktofel/Archipelago#115]
### What happened?

![456456456](https://github.com/Ziktofel/Archipelago/assets/93214632/faa3a09a-3ceb-43e5-84ac-02755ebd6494)
![4565467](https://github.com/Ziktofel/Archipelago/assets/93214632/ae5b8848-a89a-4497-9cbb-fc3d72b4ca10)
Slayer has a passive ability that allows him to ignore damage for the first 2 seconds after receiving damage.
1) This ability does not work. Slayer took damage and then continued to take damage for the next 2 seconds.
2) The description of the debuff/buff is not correct.

### What were the expected results?

Fix Phasing Armor ability.

### Software

While playing

**Comment by Ziktofel** [comment]
Failed to reproduce: After getting hit, the slayer is invulnerable for a short while and can't be attacked:
![Snímek obrazovky pořízený 2023-12-18 22-35-06](https://github.com/Ziktofel/Archipelago/assets/3447808/7f7d5c94-8385-4433-bc4d-376f607ed615)

**Comment by Ziktofel** [comment]
Failed to reproduce
