### ISSUE TITLE
Bug: Creep Tumors don't create propagation tentacle effects

### ISSUE THREAD

**Issue by MatthewMarinets** [Ziktofel/Archipelago#116]
### What happened?

When spreading a creep tumor, the new tumor spawned into existence without the usual tentacle projectile.

### What were the expected results?

Normally, the casting creep tumor shoots a tentacle projectile towards the new location, and the new creep tumor starts building when it lands.

### Software

While playing

**Comment by Ziktofel** [comment]
Fixed in latest commits of the mod
