### ISSUE TITLE
Bug: Specter Bunker Bug

### ISSUE THREAD

**Issue by Varcklen** [Ziktofel/Archipelago#117]
### What happened?

![67867867](https://github.com/Ziktofel/Archipelago/assets/93214632/734131bf-61d3-4d32-9a55-377cb01e5b2c)
If there are 4 Specters in a bunker (fully upgraded bunker, each of them takes up 1 slot), then units cannot occupy the remaining 2 slots.

### What were the expected results?

Fix it

### Software

While playing

**Comment by Ziktofel** [comment]
unable to reproduce, try `/download_data`

**Comment by Ziktofel** [comment]
![Snímek obrazovky pořízený 2023-12-16 01-03-16](https://github.com/Ziktofel/Archipelago/assets/3447808/7c11fc5e-b2d9-4bed-a00f-91731944ea87)
