### ISSUE TITLE
Bug: Templar's Return bugs

### ISSUE THREAD

**Issue by MatthewMarinets** [Ziktofel/Archipelago#120]
### What happened?

Issues from my last playthrough of the mission 2023-12-26
* Templar's Return -- segment 1, north Vorazun stealth section, a patrolling overseer wouldn't move making it impossible without SOA
  * I think the vorazun voiceline notifying the player to go there didn't trigger at all, so it's possible an earlier trigger failed to start the patrol paths
* Templar's Return -- segment 2, stealing colossus gives segment 3 purifier check
* Templar's Return -- segment 2, building zealots gives segment 3 DT check
* Templar's Return -- building any gateway units in segment 2 gives them to you in segment 3

This overseer wouldn't move:
![Screenshot2023-12-26 22_16_39](https://github.com/Ziktofel/Archipelago/assets/31861583/949daa0a-bdb6-41c4-a1ba-6ca03f207017)

I got the first segment 3 check after mind-controlling a colossus in segment 2:
![Screenshot2023-12-26 22_24_31](https://github.com/Ziktofel/Archipelago/assets/31861583/0e774189-f4b2-4551-a582-71e1ed04be46)

### What were the expected results?

* For overseers to properly patrol in stealth sections (I had to use timestop to get through it, which isn't an option without the SOA in no-build option)
* For checks and units to be properly localized to their segments

### Software

While playing

**Comment by Ziktofel** [comment]
Didn't @EnvyDragon fix that?

**Comment by EnvyDragon** [comment]
Believe so, haven't seen anyone test it though (other than me)
