### ISSUE TITLE
Bug: Command-Card priority bugs

### ISSUE THREAD

**Issue by MatthewMarinets** [Ziktofel/Archipelago#121]
### What happened?

* several protoss missions (Amon's Reach, Rak'Shir) -- second Nexus has different command-card tab than first nexus
  * Similar issue with the orbital command -- I have to manually tab to use abilities on the non-main orbital command or build SCVs from there
  * BicolourSnake has noted in the discord that this issue is present with hatcheries as well
* Ravager has higher command-card priority than kerrigan
* Supplicants have higher command-card priority than karax / fenix

### What were the expected results?

* All nexi should have the same command-card tab, so I can build probes from all of them without having to tab between them
* Supplicants should have lower command-card priority than heroes (or anything with an ability)
* I actually liked having ravagers with higher priority than kerrigan, as it encouraged using army abilities, with Kerrigan abilities still easily accessible with the hero-select hotkey. It would be better if it was consistent, though, with defilers, infestors, and other units with abilities (corruptors) also getting higher priority than kerrigan

![Screenshot2023-12-26 19_58_21](https://github.com/Ziktofel/Archipelago/assets/31861583/4aefe535-f815-43bb-8e7d-a2a1f83a393a)
Note the "Queue is full" from trying to build probes, when the second Nexus hasn't filled its queue.

### Software

While playing

**Comment by Bicoloursnake** [comment]
Hopping in here to report the Town Hall tab issue can also happen with hatcheries, and that I also experienced it with Orbital commands.

**Comment by MatthewMarinets** [comment]
Unit selection priority issues should be resolved by [PR 76](https://github.com/Ziktofel/Archipelago-SC2-data/pull/76). Orbital command abilities not being shared across subgroups is still an issue as far as I know.

**Comment by Ziktofel** [comment]
The PR adressing that got merged, so it should be fixed then
