### ISSUE TITLE
Bug: [Rak'Shir] Opening cinematic is delayed until after Artanis's first voiceline

### ISSUE THREAD

**Issue by MatthewMarinets** [Ziktofel/Archipelago#123]
### What happened?

Starting Rak'shir, the opening cinematic wouldn't play immediately and units would stand around / probes would not mine. Artanis would give a during-gameplay voiceline, during which time I send probes to start mining and can start macroing. Only after that first voiceline does the opening cinematic play

### What were the expected results?

The opening cinematic should play immediately, and Artanis's voiceline should only go afterwards.

### Software

While playing

**Comment by EnvyDragon** [comment]
Should be fixed btw, someone can test if desired
