### ISSUE TITLE
Bug: Mass Recall Bug on Harvest of Screams

### ISSUE THREAD

**Issue by Bicoloursnake** [Ziktofel/Archipelago#126]
### What happened?

When using the Spear of Adun to mass recall my units in Harvest of Scream, I got an error about a missing primary Nexus.

### What were the expected results?

My units would be recalled home.

### Software

While playing

**Comment by MatthewMarinets** [comment]
In the discord, Snappyadoo just reported a similar issue on Phantoms in the Void.
> ok yeah for sure mass recall does not work on narud3

https://discord.com/channels/731205301247803413/980554570075873300/1225311729068671038

**Comment by MatthewMarinets** [comment]
Snappyadoo also reported the same recall issue on Harbinger of Oblivion
>also... mass recall does not work on harbinger of oblivion, which is weird since it should work in the base game

https://discord.com/channels/731205301247803413/980554570075873300/1225327067080425492
