### ISSUE TITLE
Bug: Generated a bunch of Nova Equipment with no Nova missions.

### ISSUE THREAD

**Issue by Bicoloursnake** [Ziktofel/Archipelago#127]
### What happened?

During generation, I got a bunch of Nova Equipment and I was sad to not have any Nova.

[Starcraft 2.zip](https://github.com/Ziktofel/Archipelago/files/13910235/Starcraft.2.zip)

### What were the expected results?

Either a Nova mission would be included in the mission pool or no Nova equipment would be in the item pool.

### Software

Local generation

**Comment by Ziktofel** [comment]
Should be fixed

**Comment by Bicoloursnake** [comment]
Fetched the updates and generated with the same seed, no Nova items appeared this time. Thanks!
