### ISSUE TITLE
Bug: Baneling's Centrifugal Hooks requires upgrade

### ISSUE THREAD

**Issue by Varcklen** [Ziktofel/Archipelago#129]
### What happened?

![4565657](https://github.com/Ziktofel/Archipelago/assets/93214632/bd8547d3-496a-44e0-9703-95d4f5b51e78)

Baneling's Centrifugal Hooks requires learning upgrade, which cannot be learned.
Mode Version by ~12.01.24

### What were the expected results?

Fix

### Software

While playing

**Comment by Ziktofel** [comment]
That got already fixed
