### ISSUE TITLE
Vanilla Bug: Destroyed Thors are bigger than normal Thors

### ISSUE THREAD

**Issue by Them8** [Ziktofel/Archipelago#13]
### What happened?

When i thor dies its wreakage is bigger than the thor. when the thor dies it grows
![image](https://github.com/Ziktofel/Archipelago/assets/45337294/40d5c7b2-82ab-4852-8366-b4042f6044ae)

### What were the expected results?

the thor wreakage beeing the same size as the thor.

### Software

While playing

**Comment by Ziktofel** [comment]
I think it can be actually fixed by Actor model scaling, just find the proper scale

**Comment by Them8** [comment]
the actor for thors is 0.50000 while for wrecked thors its 0.65000 for some reason

**Comment by Ziktofel** [comment]
Can you test setting the value to `0.5` for the wreck?

**Comment by Ziktofel** [comment]
Looks like Blizz was playing for the Thor size over time
