### ISSUE TITLE
Bug: Planetfall "Bile Launches Deployed 2-5" doesn't work

### ISSUE THREAD

**Issue by Varcklen** [Ziktofel/Archipelago#130]
### What happened?

![345645667](https://github.com/Ziktofel/Archipelago/assets/93214632/354a1fa2-fd72-4bc3-82aa-460d4fe43893)

Bile Launchers are created in the mission over time. At the result, the mission is completed, but progress is not counted.

Mode Version by ~12.01.24

### What were the expected results?

Fix

### Software

While playing

**Comment by Ziktofel** [comment]
That was already fixed, updating the package
