### ISSUE TITLE
Bug: The Liberation Day: Transport extra check fails to activate

### ISSUE THREAD

**Issue by ArchonofFail** [Ziktofel/Archipelago#140]
### What happened?

I finished the Liberation Day mission on a fresh vanilla shuffled game twice and despite destroying the transport, the check never activated.

### What were the expected results?

The check presumably should activate upon destroying the transport towards the end of the mission.

### Software

While playing

**Comment by Ziktofel** [comment]
![Snímek obrazovky pořízený 2024-01-28 13-28-45](https://github.com/Ziktofel/Archipelago/assets/3447808/3605e03f-1aa9-494d-8a8c-e789d183252c)
Failed to reproduce
