### ISSUE TITLE
Bug: Shadow Ops has the tooltip for the Ghost Academy in the build menu

### ISSUE THREAD

**Issue by ArchonofFail** [Ziktofel/Archipelago#141]
### What happened?

In the advanced building menu, the description of the shadow ops building says that it can build nukes that ghosts can use and enables building ghosts at the barracks.
![SC2_x64_pk6wGpgaWy](https://github.com/Ziktofel/Archipelago/assets/5864577/8c60df78-58c5-4277-9f9d-19c062d32b42)

### What were the expected results?

The descriptions should instead reference specters which is what it actually enables.

### Software

While playing

**Comment by Ziktofel** [comment]
It enables both Ghosts and Spectres (and nukes can be launched by either Ghost or Spectre)

**Comment by ArchonofFail** [comment]
The tooltip should probably reflect that then because it's confusing having it just say ghosts when you only have spectres unlocked as was the case here.
