### ISSUE TITLE
Bug: [Lab Rat] Gas turrets don't damage zerglings under some conditions

### ISSUE THREAD

**Issue by MatthewMarinets** [Ziktofel/Archipelago#149]
### What happened?

[Originally reported by sweetox in the discord](https://discord.com/channels/731205301247803413/1101186175722598521/1200526136883552256). Zerglings don't take damage from the gas turrets _sometimes_.

Conditions under which zerglings don't take damage aren't fully known. Current hypothesis is that it's difficulty-based; Hopop and sweetox both reported no damage and both play normal, myself Phanerus (Phanerus) and Bicoloursnake play on hard/brutal and _did_ see damage.

### What were the expected results?

Zerg units are consistently damaged by the gas chamber.

### Software

While playing

**Comment by Ziktofel** [comment]
![Snímek obrazovky pořízený 2024-01-28 15-52-01](https://github.com/Ziktofel/Archipelago/assets/3447808/c3d40092-5d6e-4120-86e4-ac28e739c84f)
According to map file, the gas damage is only on hard+ (it's mentioned in several places)

(Not a Bug)
