### ISSUE TITLE
Bug: Nova displays stim icon even without stim unlocked if another selected unit has stim

### ISSUE THREAD

**Issue by MatthewMarinets** [Ziktofel/Archipelago#163]
### What happened?

Originally reported by IncoherentOrange:
> When you have units with Stimpak unlocked in a control group with Nova, it displays Nova's Stim Infusion ability as available. This is similar to the effect of stimpak or cloak appearing on all applicable unit cards when one of them has it, but maybe it especially shouldn't there.

Salzkorn's initial response:
> I think that's something we have no control over, unless we completely disallow nova stim from also triggering other stims, which I don't think would be desirable

IncoherentOrange:
> Maybe Nova can have the regular stimpack icon without having the actual ability so I don't have to remind myself I have no super stim units

I think the proposed solution is a good one; it ensures the player can still activate stim on all units when Nova has stim; and improves usability in that it can show the damaging stim icon if nova herself doesn't have super stim.

This should be easy to accomplish by just giving Nova a stim button in the same slot as super stim, with a button requirement that will never be true. `AP_Never` can be implemented by e.g. checking if 0 is equal to 1.

### What were the expected results?

Nova doesn't display the healing stim icon if she doesn't have stim.

### Software

While playing

**Comment by Ziktofel** [comment]
I've changed the icon and description of the button if the Nova's ability is not yet acquired
