### ISSUE TITLE
Bug: Compiled mind-control AI issues

### ISSUE THREAD

**Issue by MatthewMarinets** [Ziktofel/Archipelago#164]
### What happened?

Mind controlling units in many missions doesn't turn off their AI commands. Trying to compile the issues I've seen mentioned, may be missing some:
- [x] **Enemy Within** Sentries forcefielding the area after the warp drive is destroyed continue to force-field after mind control (--BicolourSnake)
- [x] **Flashpoint** Zerg will periodically a-move into your base after being mind-controlled
- [x] **Enemy Intelligence** Zerg will periodically a-move into your base after being mind-controlled
- [x] **The Escape** Mind-controlled units attacking Nova will continue attacking her after being dominated; may also be good to check scripted events / retreats don't still affect mind-controlled units

### What were the expected results?

Mind-controlled units should not be subject to AI triggers / commands.

### Software

While playing

**Comment by EnvyDragon** [comment]
Amon's Reach - Patrolling Overseers go back to patrolling
Growing Shadow - Mind-controlling the end protoss doesn't remove them from the unit group that gets checked for victory, so you need to kill them manually

**Comment by Ziktofel** [comment]
I've tried to address all these instances

**Comment by Ziktofel** [comment]
All of those are already fixed and nothing else is reported. Closing
