### ISSUE TITLE
Bug: Enemy AI flawlessly avoids Ravager's Corrosive Bile

### ISSUE THREAD

**Issue by AliceVoltaire** [Ziktofel/Archipelago#165]
### What happened?

AI is impossibly perfect at avoiding Corrosive Bile.

### What were the expected results?

It is nearly impossible to actually hit enemy units with Corrosive Bile, which severely undermines the value of morphing Ravagers to begin with.  Why bother morphing them, when Roaches can wipe out enemy units a lot more efficiently?  This behavior should probably be changed, as none of the vanilla campaigns ever expected you to have Ravagers and I'd like them to actually be useful in the randomizer.

### Software

While playing

**Comment by Ziktofel** [comment]
Disruptors have similar problem

**Comment by EnvyDragon** [comment]
And Banelings. Including when they're burrowed. They almost end up as an invisible forcefield.

**Comment by MatthewMarinets** [comment]
I have local changes I've tested and am happy with for ravagers and disruptors. Can have a PR up in a few minutes

**Comment by MatthewMarinets** [comment]
Made PR [#95](https://github.com/Ziktofel/Archipelago-SC2-data/pull/95) to deal with ravager and disruptor issue, as well as getting that firebat damage point fix in. These are all "game feel" fixes to me, I've been using them throughout most of my beta async playthrough and they all feel much better.

**Comment by MatthewMarinets** [comment]
Made [PR #95](https://github.com/Ziktofel/Archipelago-SC2-data/pull/95) to deal with ravager and disruptor issue, as well as getting that firebat damage point fix in. These are all "game feel" fixes to me, I've been using them throughout most of my beta async playthrough and they all feel much better.

**Comment by Ziktofel** [comment]
PR Merged, closing as Fixed
