### ISSUE TITLE
Mission Order Generation: better race / difficulty balancing for missions

### ISSUE THREAD

**Issue by MatthewMarinets** [Ziktofel/Archipelago#179]
## Difficulty balancing
Currently, if a yaml selects a mission order that requires e.g. 3 starter/easy missions (e.g. grid), and all but 1 starter/easy missions are excluded with `excluded_missions`, generation will just fail. A more robust solution would be able to dynamically shuffle harder missions into easier pools to hit certain watermarks for each pool size, so generation should only fail if the absolute number of available missions is insufficient.

This behaviour should be the same whether missions are excluded based on `exclude_no_builds` / enable campaign options, or based on `excluded_missions`.

I see 3 ways of determining the required pool-sizes:
* Hard-code some values, e.g. 3 starter, 3 easy, 4 normal, 5 hard.
* Allow the mission order generation to call a function to balance the pools, passing in the required pool sizes for each difficulty
* Salzkorn, 2024-03-31: "I have a solution for the difficulty thing too lmao. I just flood-fill the mission order to determine minimum amount of missions needed to reach each mission, which works pretty well as a tool for dynamically determining how difficult a mission should be"

## Race balancing
It's currently possible to get a grid mission order that includes all races but only has a small number of zerg missions. This creates a bad player experience as many zerg items will fill the pool despite having few missions to use them in. The overall amount of missions from each race should be balanced.

It may also be worth considering how to balance NCO missions, as Nova equipment can create a similar cluttering effect.

I think this is best accomplished by giving the item pool structures some state, so that if e.g. a protoss mission is pulled from the pool, the structure can remember that and vastly decrease the probability that the next selected mission is a protoss one. Different approaches can be taken to allow for clustering or impose the constraint differently to encourage randomness, but all these approaches will likely require storing some state.

## Overall
I'd propose refactoring the item pools to be some kind of class with an interface to shuffle difficulties as per section 1 and store state as per section 2. It may also be worth adding some unit tests if the unit has a well-defined interface.

**Comment by Ziktofel** [comment]
Already done by @Salzkorn
