### ISSUE TITLE
Protoss unit upgades

### ISSUE THREAD

**Issue by Ziktofel** [Ziktofel/Archipelago#32]
### What feature would you like to see?

- Leg Enhancement (Zealot) - Zealot speed
- Singularity Charge (Dragoon) - Dragoon range
- Trillic Compression Systems (Dragoon) - +HP, + Shield regen
- Khaydarin Amulet (High Templar) - Energy upgrade
- Apial Sensors (Scout) - Sight range upgrade
- Gravitic Thursters (Scout) - Scout speed
- Gravitic Boosters (Observer) - Observer speed
- Sensor Array (Observer) - Observer sight range
- Khaydarin Core (Arbiter) - Arbiter Energy

**Comment by MadiMadsen** [comment]
### Melee Warriors Vanilla LotV Upgrade Ideas

Melee Warriors: 
Zealot, Aiur Zealot, Centurion,  Sentinel
Group upgrade: movement speed buff: Leg Enhancement

indivudal upgrades:

- Zealot1: easy mode: +2 damage against light units

- Zealot1 Charge: hard mode: block their charge behind charge upgrade

- Zealot2: +25 shield to zealot

- Aiur Zealot1 Valorous Inspirator: inrease the whirlwind damage from 35 to 70

- Aiur Zealot2: Basic attack does splash in front of unit equal to 50% of their damage

- Centurion1 Withering Siphon: Darkcoil affects Massive/Heroic/Unstoppable units and causes enemy units to lose 5 hit points every 0.25 second, up to a maximum of 50. This effect cannot kill

- Centurion2: This Unit is cloaked until it attacks an enemy.

- Sentinel1: When Reconstruction is finished This unit will have 5 seconds of invulenerability.

- Sentinel2: This unit will slowly regenerate health 1 hp/s.

**Comment by MatthewMarinets** [comment]
I'd like to see Chrono Boost unlockable in the WoL protoss missions. Compatibility with original WoL is maintained by just banning it (or putting it in ext), and it leaves the door open in LotV for leaving it unlockable or having it always unlocked for LotV missions.

**Comment by Ziktofel** [comment]
There won't be any mission-based unlock. it'd be either upgrade or allowed everywhere when LotV lands

**Comment by Ziktofel** [comment]
Protoss unit upgrades are in
