### ISSUE TITLE
Bug: Media Blitz, Starport and Secret Mission checks not marked as [Done] in game

### ISSUE THREAD

**Issue by Matiya-star** [Ziktofel/Archipelago#46]
### What happened?

Neither Starport or Secret Mission check were marked as [Done] on the in game tracker, Starport check was done during sneak attack, Secret Mission check done after it was over. Done on Brutal difficulty.

![image](https://github.com/Ziktofel/Archipelago/assets/128200488/47abc05f-d6f0-42ae-996c-d9bf4e714497)

### What were the expected results?

Everything to mark as [Done]

### Software

While playing

**Comment by MatthewMarinets** [comment]
Confirmed fixed on sc2-next by BicolourSnake in the discord:
> It's fixed on the sc2-next version.

**Comment by Ziktofel** [comment]
Reported as already fixed
