### ISSUE TITLE
Bug: Dark Templar Shadow Fury has no AoE display

### ISSUE THREAD

**Issue by Matiya-star** [Ziktofel/Archipelago#47]
### What happened?

Using Shadow Fury on Sinister Turn does not have an aoe effect before casting indicator like it does in LotV. Could be other misssions as well but definitely Sinister Turn

### What were the expected results?

^

### Software

While playing

**Comment by Ziktofel** [comment]
Fixed

![Snímek obrazovky pořízený 2023-07-30 12-14-22](https://github.com/Ziktofel/Archipelago/assets/3447808/f3eacc2e-7a70-4ef2-a1d3-24707b114d69)
