### ISSUE TITLE
Bug: Hellbat Aspect (Hellion) not in the item pool

### ISSUE THREAD

**Issue by MaxTousss** [Ziktofel/Archipelago#48]
### What happened?

The upgrade Hellbat Aspect (Hellion) was not available in the item pool even though Hellion were in the unit pool, NCO was enabled and "units have all upgrades" was enabled. The yaml is available in the sc2 Beta of 23/07/26, it is named 23_07_26_dsa_sc2.yaml. 

When using hint for that item, it claimed "not in the multiworld".

Note: The same happened with the upgrades of Goliath for Hopo (see Hopop-NCO)

### What were the expected results?

That the upgrade "Hellbat Aspect (Hellion)" would be available somewhere in the multiworld.

### Software

While playing

**Comment by Ziktofel** [comment]
Fixed. I think this might happen in Release too
