### ISSUE TITLE
Bug: Fire in the Sky 3 Gorgon Check

### ISSUE THREAD

**Issue by NobleXenon** [Ziktofel/Archipelago#72]
### What happened?

Found the Destroy 3 Gorgons check seconds after starting the mission Fire in the Sky. Main objective counter does also display as having destroyed 3 so far.

Mission is being run using the attached yaml 
[x.yaml.txt](https://github.com/Ziktofel/Archipelago/files/13198781/x.yaml.txt)

### What were the expected results?

No check should be cleared until the correct amount of Gorgons have been destroyed

### Software

Website

**Comment by NobleXenon** [comment]
Oops, the software part is supposed to show ingame.

Anyway, other effects:
A total of 4 Gorgons actually spawn (might be 3, wasnt keeping strict count)
After the "last" Gorgon is killed, they stop spawning at all
Mission completes after the the last scourge nest is revived

**Comment by Ziktofel** [comment]
Fixed
