### ISSUE TITLE
Additional starting units

### ISSUE THREAD

**Issue by Ziktofel** [Ziktofel/Archipelago#74]
### What feature would you like to see?

From: https://discord.com/channels/731205301247803413/980554570075873300/1168628113593340014
> as far as additional common units are concerned:
Standard: No changes (Marine, Marauder, Goliath, Hellion, Vulture)
Advanced: Standard + Reaper, Diamondback, Viking, *Siege Tank, Banshee, Thor, Battlecruiser, Cyclone*
No Logic: Additional set used only for placing starter unit on no logic, all previous units + *Firebat, Ghost, Spectre, Wraith, Raven, Predator, Liberator*

**Comment by Ziktofel** [comment]
Outlaws, Evacuation
```python
    def _sc2wol_has_early_tech(self, multiworld: MultiWorld, player: int):
        return (
            self.has_any({ItemNames.MARINE, ItemNames.FIREBAT, ItemNames.MARAUDER, ItemNames.REAPER, ItemNames.HELLION}, player)
            or (self._sc2_advanced_tactics(multiworld, player) and self.has_any({ItemNames.GOLIATH, ItemNames.DIAMONDBACK, ItemNames.VIKING, ItemNames.BANSHEE}, player))
        )
```

**Comment by Magnemania** [comment]
While we're at it, I would also add these to Zerg and Protoss:

Zerg Advanced: Ultralisk
Zerg No Logic: Swarm Host, Spine Crawler

Protoss Advanced: Immortal, Void Ray, Carrier
Protoss No Logic: High Templar, Colossus

A setting suggestion, as I personally wouldn't want to start with BCs:

Change the Early Unit setting from a DefaultOnToggle to a Choice, with these options:
- Off (Mimics False behavior from before)
- Balanced (Excludes Siege Tank, Banshee, Thor, Battlecruiser, Ultralisk, Void Ray, and Carrier to avoid giving the player too much power too early)
- Any Starter Unit (uses full list)

With Balanced as the default.  This setting would not affect logic, only assign_starter_items()

**Comment by Ziktofel** [comment]
I'll deal with the Protoss once LotV gets in

**Comment by Ziktofel** [comment]
Some Protoss are already filled, closing for now
