### ISSUE TITLE
Bug: Waking the Ancient: "Absorb Primal Essence" objective not completing ingame

### ISSUE THREAD

**Issue by Magnemania** [Ziktofel/Archipelago#75]
### What happened?

Primal Essence checks are sending out correctly, but the objective text ingame is not updating after collecting the third essence.

![image](https://github.com/Ziktofel/Archipelago/assets/89949176/c1bd8b47-2ab4-4ddb-9723-ed89d5333229)

This is not caused by a specific essence; the third one collected will always fail to update the counter, regardless of which one is collected last.

### What were the expected results?

Completion of the bonus objective ingame.

### Software

While playing

**Comment by Gemster312** [comment]
Resolved with the new Objective Categorization update.
https://github.com/Ziktofel/Archipelago-SC2-data/pull/177

![image](https://github.com/user-attachments/assets/cc2f4c4d-9204-4546-98f7-16d41a3c95a6)
