### ISSUE TITLE
Balance: Rocket Barrage (Banshee) Overtuned

### ISSUE THREAD

**Issue by Magnemania** [Ziktofel/Archipelago#76]
### What feature would you like to see?

![image](https://github.com/Ziktofel/Archipelago/assets/89949176/20b75352-dccb-473c-8450-825027095dee)

This ability belongs to the Covert Banshee, which is a unit that costs 350 minerals and 187.5 gas to deploy (along with Nova's many other economic limitations in co-op) and is grossly overpowered on a unit that costs 150 minerals and 100 gas (and was already a strong unit at base).  Co-op Nova's units are meant to be particularly strong for their cost, too.

Possible rebalances:

15s cooldown, 12 damage per unit:  This preserves the constant-use nature of the ability and mimics the Banshee's base damage.  This is exactly enough damage for three Banshees to OHKO a group of Zerglings.

60s cooldown, 25 damage per unit:  This is enough damage for two Banshees to OHKO Marines (add another Banshee for Combat Shields).  Slightly less friendly to autocast.

100 energy, no cooldown, no autocast, 75 damage per unit:  Preserves original damage.  This provides an alternate use for Banshee energy and synergizes with many of their upgrades (provides an alternative use for energy after obtaining Cross Spectrum Dampeners, Cellular Reactor allows storing a second cast).  Reflects behavior of Thor's 330m cannon, but easier to use due to instant cast time and burst damage.

**Comment by Ziktofel** [comment]
There's also Viking's WILD missiles that might have the same problem too

**Comment by Ziktofel** [comment]
Option 1 and 2 - Too weak IMHO - problems with overlapping with the splash upgrade
Option 3 - That'd require dropping from Progression to Useful (as all logic rules expect the current power)

**Comment by Magnemania** [comment]
I am fine with dropping from Progression to Useful, using attacking units to defend is somewhat unintuitive as it is.

**Comment by Ziktofel** [comment]
Done
