### ISSUE TITLE
Bug: The Infinite Cycle: Second Xel'Naga Device not sending

### ISSUE THREAD

**Issue by hopop201** [Ziktofel/Archipelago#87]
### What happened?

When you are collecting the Xel'Naga devices on The Infinite Cycle, the location for the Third Xel'Naga Device is sent when you pick up the second device in the mission and the Second Xel'Naga Device location does not send at all.

### What were the expected results?

Collecting the second device sends the Second Xel'Naga Device location.
Collecting the thirddevice sends the Third Xel'Naga Device location.

### Software

While playing

**Comment by Ziktofel** [comment]
Fixed
