### ISSUE TITLE
Bug: Can build Stargate when it  has no purpose

### ISSUE THREAD

**Issue by hopop201** [Ziktofel/Archipelago#88]
### What happened?

Currently have no Air units, and one level of Air weapon upgrades. Able to build a Stargate.
Happened on Spear of Adun.

### What were the expected results?

Not able to build a Stargate

### Software

While playing

**Comment by MatthewMarinets** [comment]
Checking the triggers in `LibABFE498B.galaxy`, function `libABFE498B_gf_AP_Triggers_Protoss_unlockAirWeapons()`, looks like stargate is awarded if air weapons (or air armour) is level >= 1 AND `AP_Triggers_isGenericUpgradeAutoUnlock` is false (alongside the cybernetics core). Nothing gets unlocked in `generic_upgrade_auto_unlock` is true, and the fleet beacon (which I think is required for later upgrades?) is not given.

Checking AbilData.xml / RequirementData.xml, it looks like no Protoss air upgrades require stargate or fleet beacon, so I think it's safe to remove the lines granting the stargate for air upgrades.

**Comment by Ziktofel** [comment]
it's for unlocking Cyber Core as if you don't own a Gateway unit, Gateway isn't available, it's the same as unlocking Armory
