### ISSUE TITLE
Bug: Spear of Adun Unpowered Gateways not getting powered

### ISSUE THREAD

**Issue by hopop201** [Ziktofel/Archipelago#89]
### What happened?

If you build a pylon next to the unpowered gateways on the Spear of Adun map, the Gateways are not powered and the locations are not sent.

### What were the expected results?

The gateways are powered and the corresponding locations are sent.

### Software

While playing

**Comment by hopop201** [comment]
Madi has already been told directly and they know how to fix it. :P

**Comment by Ziktofel** [comment]
Fixed
