### ISSUE TITLE
Bug: The Growing Shadow crashes upon Victory

### ISSUE THREAD

**Issue by AliceVoltaire** [Ziktofel/Archipelago#94]
### What happened?

The game hard crashes immediately upon reaching Artanis on The Growing Shadow.  The location still sent so it isn't detrimental, but the game should not crash like that before playing out the cutscene.

### What were the expected results?

not to crash

### Software

While playing

**Comment by Ziktofel** [comment]
I get this screen in this mission: Not reproduced
![Snímek obrazovky pořízený 2023-11-15 20-09-36](https://github.com/Ziktofel/Archipelago/assets/3447808/59284ac6-987b-42c8-bfb8-a75ed496feb2)
