### ISSUE TITLE
Bug: The Host 

### ISSUE THREAD

**Issue by NobleXenon** [Ziktofel/Archipelago#98]
### What happened?

All units and structures seem to be their melee variants, complete with upgrades (ie research for hallucination on the cybernetics core). Only exceptions seem to be the structures behaving closer to their 'vanilla' campaign variants, so gateways automatically get warpgate despite there being a research, no twilight council for templar archives, etc.

Also Spear of Adun is there and does work correctly.

### What were the expected results?

Everything should be its corresponding AP unit. Mission should work the same as the other AP missions wrt to units, structures, and unlocks.

### Software

While playing

**Comment by Ziktofel** [comment]
Looks like fixed.
